[package]
name = "foxin"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.0", default-features = false }
crossterm = "0.27.0"
ratatui = { version = "0.26.1", features = ["unstable-widget-ref"] }
